services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  nginx_proxy:
    image: nginx:latest
    ports:
      - "8000:80"

    volumes:
      - "src/main/resources/nginx.conf:usr/share/nginx/html"